version: "3.9"
services:
  flask-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./saved_models:/app/saved_models
    networks:
      - mt-network

  streamlit-ui:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - flask-api
    networks:
      - mt-network

networks:
  mt-network:
